targets:
  $default:
    builders:
      riverpod_generator:
        options:
          # Generate riverpod providers with @riverpod annotation
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake
      freezed:
        options:
          when: true
