import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';

/// SeedDataRunner — Script nạp dữ liệu mẫu (Seed Data) vào Firestore
class SeedDataRunner {
  static final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  /// Chạy nạp toàn bộ dữ liệu mẫu
  static Future<void> runSeed() async {
    debugPrint('🚀 Đang bắt đầu nạp Seed Data vào Firestore...');

    await _seedCategories();
    await _seedBanners();
    await _seedProducts();
    await _seedAdminUser();

    debugPrint('✅ Nạp Seed Data thành công!');
  }

  // ─── 1. Danh Mục (Categories) ──────────────────────────────────────────────
  static Future<void> _seedCategories() async {
    final categories = [
      {
        'id': 'cat_iphone',
        'name': 'iPhone',
        'iconURL': 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=200',
        'order': 1,
        'productCount': 6,
      },
      {
        'id': 'cat_samsung',
        'name': 'Samsung',
        'iconURL': 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=200',
        'order': 2,
        'productCount': 5,
      },
      {
        'id': 'cat_xiaomi',
        'name': 'Xiaomi',
        'iconURL': 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=200',
        'order': 3,
        'productCount': 5,
      },
      {
        'id': 'cat_oppo',
        'name': 'OPPO',
        'iconURL': 'https://images.unsplash.com/photo-1580910051074-3eb694886505?w=200',
        'order': 4,
        'productCount': 4,
      },
      {
        'id': 'cat_accessory',
        'name': 'Phụ kiện',
        'iconURL': 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=200',
        'order': 5,
        'productCount': 3,
      },
    ];

    final batch = _firestore.batch();
    for (final cat in categories) {
      final docRef = _firestore.collection('categories').doc(cat['id'] as String);
      batch.set(docRef, {
        'name': cat['name'],
        'iconURL': cat['iconURL'],
        'order': cat['order'],
        'productCount': cat['productCount'],
      });
    }
    await batch.commit();
    debugPrint('✓ Đã tạo ${categories.length} danh mục');
  }

  // ─── 2. Banners ─────────────────────────────────────────────────────────────
  static Future<void> _seedBanners() async {
    final banners = [
      {
        'id': 'banner_1',
        'imageURL': 'https://images.unsplash.com/photo-1556656793-08538906a9f8?w=1200',
        'targetType': 'category',
        'targetId': 'cat_iphone',
        'isActive': true,
        'order': 1,
      },
      {
        'id': 'banner_2',
        'imageURL': 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=1200',
        'targetType': 'category',
        'targetId': 'cat_samsung',
        'isActive': true,
        'order': 2,
      },
      {
        'id': 'banner_3',
        'imageURL': 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=1200',
        'targetType': 'external_url',
        'targetId': '',
        'isActive': true,
        'order': 3,
      },
    ];

    final batch = _firestore.batch();
    for (final banner in banners) {
      final docRef = _firestore.collection('banners').doc(banner['id'] as String);
      batch.set(docRef, {
        'imageURL': banner['imageURL'],
        'targetType': banner['targetType'],
        'targetId': banner['targetId'],
        'isActive': banner['isActive'],
        'order': banner['order'],
      });
    }
    await batch.commit();
    debugPrint('✓ Đã tạo ${banners.length} banners');
  }

  // ─── 3. Sản Phẩm (20+ Products) ──────────────────────────────────────────────
  static Future<void> _seedProducts() async {
    final now = DateTime.now();
    final products = [
      // --- Apple / iPhone ---
      {
        'id': 'prod_iphone15promax',
        'name': 'iPhone 15 Pro Max 256GB',
        'brand': 'Apple',
        'category': 'cat_iphone',
        'description': 'Khung Titan siêu bền nhẹ, Chip A17 Pro mạnh mẽ đỉnh cao, nút Action mới và hệ thống camera 5x đẳng cấp.',
        'price': 34990000.0,
        'discountPrice': 29990000.0,
        'images': [
          'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800',
          'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=800',
        ],
        'specs': {
          'Màn hình': '6.7 inch, Super Retina XDR OLED, 120Hz',
          'Chipset': 'Apple A17 Pro (3 nm)',
          'RAM': '8 GB',
          'Bộ nhớ trong': '256 GB',
          'Pin': '4422 mAh, Sạc nhanh 20W',
          'Camera sau': '48 MP + 12 MP + 12 MP',
        },
        'colors': ['Titan Tự Nhiên', 'Titan Xanh', 'Titan Đen', 'Titan Trắng'],
        'stock': 45,
        'sold': 120,
        'rating': 4.9,
        'reviewCount': 85,
        'tags': ['featured', 'best_seller', 'apple'],
        'isActive': true,
        'isFeatured': true,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'prod_iphone15pro',
        'name': 'iPhone 15 Pro 128GB',
        'brand': 'Apple',
        'category': 'cat_iphone',
        'description': 'Thiết kế Titan cao cấp, Chip A17 Pro thế hệ mới, cổng sạc USB-C truyền dữ liệu siêu tốc.',
        'price': 28990000.0,
        'discountPrice': 25490000.0,
        'images': [
          'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800',
        ],
        'specs': {
          'Màn hình': '6.1 inch, Super Retina XDR OLED, 120Hz',
          'Chipset': 'Apple A17 Pro (3 nm)',
          'RAM': '8 GB',
          'Bộ nhớ trong': '128 GB',
          'Pin': '3274 mAh',
        },
        'colors': ['Titan Tự Nhiên', 'Titan Đen'],
        'stock': 30,
        'sold': 64,
        'rating': 4.8,
        'reviewCount': 42,
        'tags': ['apple', 'pro'],
        'isActive': true,
        'isFeatured': false,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'prod_iphone15',
        'name': 'iPhone 15 128GB',
        'brand': 'Apple',
        'category': 'cat_iphone',
        'description': 'Màn hình Dynamic Island hiện đại, camera chính 48MP sắc nét, mặt lưng kính pha màu cuốn hút.',
        'price': 22990000.0,
        'discountPrice': 19690000.0,
        'images': [
          'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800',
        ],
        'specs': {
          'Màn hình': '6.1 inch OLED, Dynamic Island',
          'Chipset': 'Apple A16 Bionic',
          'RAM': '6 GB',
          'Bộ nhớ trong': '128 GB',
        },
        'colors': ['Hồng', 'Xanh Lá', 'Vàng', 'Đen'],
        'stock': 50,
        'sold': 110,
        'rating': 4.7,
        'reviewCount': 56,
        'tags': ['best_seller', 'apple'],
        'isActive': true,
        'isFeatured': true,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'prod_iphone14promax',
        'name': 'iPhone 14 Pro Max 128GB',
        'brand': 'Apple',
        'category': 'cat_iphone',
        'description': 'Màn hình Always-On Display, Dynamic Island đột phá, camera 48MP và cảm biến A16 Bionic.',
        'price': 27990000.0,
        'discountPrice': 24990000.0,
        'images': [
          'https://images.unsplash.com/photo-1663499482523-1c0c1bae4ce1?w=800',
        ],
        'specs': {
          'Màn hình': '6.7 inch, Super Retina XDR OLED, 120Hz',
          'Chipset': 'Apple A16 Bionic',
          'RAM': '6 GB',
          'Bộ nhớ trong': '128 GB',
        },
        'colors': ['Tím Đậm', 'Vàng', 'Bạc', 'Đen'],
        'stock': 20,
        'sold': 210,
        'rating': 4.8,
        'reviewCount': 130,
        'tags': ['apple'],
        'isActive': true,
        'isFeatured': false,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'prod_iphone13',
        'name': 'iPhone 13 128GB',
        'brand': 'Apple',
        'category': 'cat_iphone',
        'description': 'Thiết kế thời thượng, chip A15 Bionic mượt mà, thời lượng pin vượt trội.',
        'price': 16990000.0,
        'discountPrice': 13790000.0,
        'images': [
          'https://images.unsplash.com/photo-1632661674596-df8be070a5c5?w=800',
        ],
        'specs': {
          'Màn hình': '6.1 inch Super Retina XDR',
          'Chipset': 'Apple A15 Bionic',
          'RAM': '4 GB',
          'Bộ nhớ trong': '128 GB',
        },
        'colors': ['Trắng', 'Đen', 'Xanh Dương', 'Hồng'],
        'stock': 40,
        'sold': 350,
        'rating': 4.9,
        'reviewCount': 220,
        'tags': ['best_seller', 'apple'],
        'isActive': true,
        'isFeatured': false,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'prod_iphone11',
        'name': 'iPhone 11 64GB',
        'brand': 'Apple',
        'category': 'cat_iphone',
        'description': 'Mẫu iPhone quốc dân giá cực tốt, camera kép chụp đêm ấn tượng, hiệu năng ổn định.',
        'price': 11990000.0,
        'discountPrice': 8990000.0,
        'images': [
          'https://images.unsplash.com/photo-1573148195900-7845dcb9b127?w=800',
        ],
        'specs': {
          'Màn hình': '6.1 inch Liquid Retina HD',
          'Chipset': 'Apple A13 Bionic',
          'RAM': '4 GB',
          'Bộ nhớ trong': '64 GB',
        },
        'colors': ['Đen', 'Trắng', 'Đỏ'],
        'stock': 15,
        'sold': 500,
        'rating': 4.7,
        'reviewCount': 310,
        'tags': ['apple', 'budget'],
        'isActive': true,
        'isFeatured': false,
        'createdAt': now,
        'updatedAt': now,
      },

      // --- Samsung ---
      {
        'id': 'prod_s24ultra',
        'name': 'Samsung Galaxy S24 Ultra 12GB/256GB',
        'brand': 'Samsung',
        'category': 'cat_samsung',
        'description': 'Quyền năng Galaxy AI đỉnh cao, khung viền Titan chắc chắn, Zoom chuẩn quang học 100x và bút S-Pen tích hợp.',
        'price': 33990000.0,
        'discountPrice': 27990000.0,
        'images': [
          'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800',
        ],
        'specs': {
          'Màn hình': '6.8 inch, Dynamic AMOLED 2X, 120Hz, 2600 nits',
          'Chipset': 'Snapdragon 8 Gen 3 for Galaxy (4 nm)',
          'RAM': '12 GB',
          'Bộ nhớ trong': '256 GB',
          'Pin': '5000 mAh, Sạc siêu nhanh 45W',
          'Camera sau': '200 MP + 50 MP + 12 MP + 10 MP',
        },
        'colors': ['Xám Titan', 'Đen Titan', 'Tím Titan', 'Vàng Titan'],
        'stock': 35,
        'sold': 95,
        'rating': 4.9,
        'reviewCount': 68,
        'tags': ['featured', 'best_seller', 'samsung', 'ai'],
        'isActive': true,
        'isFeatured': true,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'prod_s24plus',
        'name': 'Samsung Galaxy S24 Plus 12GB/256GB',
        'brand': 'Samsung',
        'category': 'cat_samsung',
        'description': 'Màn hình 2K+ sắc nét, trợ lý Galaxy AI thông minh, hiệu năng Snapdragon đỉnh cao.',
        'price': 26990000.0,
        'discountPrice': 22490000.0,
        'images': [
          'https://images.unsplash.com/photo-1584006682522-dc17d6c0d963?w=800',
        ],
        'specs': {
          'Màn hình': '6.7 inch Dynamic AMOLED 2X, 120Hz',
          'Chipset': 'Exynos 2400 / Snapdragon 8 Gen 3',
          'RAM': '12 GB',
          'Bộ nhớ trong': '256 GB',
        },
        'colors': ['Đen Onyx', 'Xám Marble', 'Tím Cobalt'],
        'stock': 25,
        'sold': 45,
        'rating': 4.7,
        'reviewCount': 30,
        'tags': ['samsung'],
        'isActive': true,
        'isFeatured': false,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'prod_zfold5',
        'name': 'Samsung Galaxy Z Fold5 12GB/256GB',
        'brand': 'Samsung',
        'category': 'cat_samsung',
        'description': 'Tuyệt tác màn hình gập không kẽ hở, bản lề Flex cải tiến, mở ra không gian làm việc và giải trí vô tận.',
        'price': 40990000.0,
        'discountPrice': 32990000.0,
        'images': [
          'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800',
        ],
        'specs': {
          'Màn hình chính': '7.6 inch Dynamic AMOLED 2X, 120Hz',
          'Màn hình phụ': '6.2 inch Dynamic AMOLED 2X',
          'Chipset': 'Snapdragon 8 Gen 2 for Galaxy',
          'RAM': '12 GB',
          'Bộ nhớ trong': '256 GB',
        },
        'colors': ['Xanh Icy', 'Đen Phantom', 'Kem Phantom'],
        'stock': 12,
        'sold': 30,
        'rating': 4.8,
        'reviewCount': 22,
        'tags': ['featured', 'samsung', 'foldable'],
        'isActive': true,
        'isFeatured': true,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'prod_zflip5',
        'name': 'Samsung Galaxy Z Flip5 8GB/256GB',
        'brand': 'Samsung',
        'category': 'cat_samsung',
        'description': 'Màn hình phụ Flex Window lớn 3.4 inch độc đáo, thiết kế gập bỏ túi nhỏ gọn thời trang.',
        'price': 25990000.0,
        'discountPrice': 17990000.0,
        'images': [
          'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800',
        ],
        'specs': {
          'Màn hình chính': '6.7 inch Full HD+ 120Hz',
          'Chipset': 'Snapdragon 8 Gen 2 for Galaxy',
          'RAM': '8 GB',
          'Bộ nhớ trong': '256 GB',
        },
        'colors': ['Xanh Mint', 'Tím Fancy', 'Kem Cream', 'Xám Graphite'],
        'stock': 20,
        'sold': 85,
        'rating': 4.6,
        'reviewCount': 48,
        'tags': ['samsung', 'foldable'],
        'isActive': true,
        'isFeatured': false,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'prod_a55',
        'name': 'Samsung Galaxy A55 5G 8GB/128GB',
        'brand': 'Samsung',
        'category': 'cat_samsung',
        'description': 'Thiết kế viền kim loại cao cấp, kháng nước IP67, camera Nightography chụp đêm rực rỡ.',
        'price': 9990000.0,
        'discountPrice': 8490000.0,
        'images': [
          'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=800',
        ],
        'specs': {
          'Màn hình': '6.6 inch Super AMOLED 120Hz',
          'Chipset': 'Exynos 1480',
          'RAM': '8 GB',
          'Bộ nhớ trong': '128 GB',
          'Pin': '5000 mAh',
        },
        'colors': ['Xanh Iceblue', 'Tím Lilac', 'Đen Navy'],
        'stock': 60,
        'sold': 180,
        'rating': 4.6,
        'reviewCount': 72,
        'tags': ['samsung', 'budget'],
        'isActive': true,
        'isFeatured': false,
        'createdAt': now,
        'updatedAt': now,
      },

      // --- Xiaomi ---
      {
        'id': 'prod_xiaomi14ultra',
        'name': 'Xiaomi 14 Ultra 16GB/512GB Leica',
        'brand': 'Xiaomi',
        'category': 'cat_xiaomi',
        'description': 'Quái thú nhiếp ảnh phối hợp cùng Leica, cụm 4 camera 50MP cảm biến 1-inch, vi xử lý Snapdragon 8 Gen 3 cực khủng.',
        'price': 32990000.0,
        'discountPrice': 29990000.0,
        'images': [
          'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800',
        ],
        'specs': {
          'Màn hình': '6.73 inch LTPO AMOLED 120Hz 2K+',
          'Chipset': 'Snapdragon 8 Gen 3',
          'RAM': '16 GB',
          'Bộ nhớ trong': '512 GB',
          'Pin': '5000 mAh, Sạc nhanh 90W',
        },
        'colors': ['Đen Da', 'Trắng Da'],
        'stock': 15,
        'sold': 40,
        'rating': 4.9,
        'reviewCount': 35,
        'tags': ['featured', 'xiaomi', 'leica'],
        'isActive': true,
        'isFeatured': true,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'prod_xiaomi14',
        'name': 'Xiaomi 14 12GB/256GB',
        'brand': 'Xiaomi',
        'category': 'cat_xiaomi',
        'description': 'Flagship nhỏ gọn đỉnh cao, ống kính Leica Summilux huyền thoại, màn hình viền siêu mỏng.',
        'price': 22990000.0,
        'discountPrice': 18990000.0,
        'images': [
          'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800',
        ],
        'specs': {
          'Màn hình': '6.36 inch OLED 120Hz',
          'Chipset': 'Snapdragon 8 Gen 3',
          'RAM': '12 GB',
          'Bộ nhớ trong': '256 GB',
        },
        'colors': ['Xanh Ngọc', 'Đen', 'Trắng'],
        'stock': 25,
        'sold': 70,
        'rating': 4.8,
        'reviewCount': 44,
        'tags': ['xiaomi'],
        'isActive': true,
        'isFeatured': false,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'prod_redminote13pro',
        'name': 'Xiaomi Redmi Note 13 Pro 5G 8GB/256GB',
        'brand': 'Xiaomi',
        'category': 'cat_xiaomi',
        'description': 'Camera 200MP siêu nét, màn hình 1.5K 120Hz, sạc siêu nhanh 67W trong phân khúc tầm trung.',
        'price': 9490000.0,
        'discountPrice': 7290000.0,
        'images': [
          'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=800',
        ],
        'specs': {
          'Màn hình': '6.67 inch AMOLED 1.5K 120Hz',
          'Chipset': 'Snapdragon 7s Gen 2',
          'RAM': '8 GB',
          'Bộ nhớ trong': '256 GB',
        },
        'colors': ['Tím Băng', 'Đen Tuyền', 'Xanh Cầu Vồng'],
        'stock': 80,
        'sold': 420,
        'rating': 4.7,
        'reviewCount': 190,
        'tags': ['best_seller', 'xiaomi', 'budget'],
        'isActive': true,
        'isFeatured': true,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'prod_redminote13',
        'name': 'Xiaomi Redmi Note 13 6GB/128GB',
        'brand': 'Xiaomi',
        'category': 'cat_xiaomi',
        'description': 'Vua phân khúc giá rẻ, màn hình AMOLED 120Hz rực rỡ, camera 108MP ấn tượng.',
        'price': 4890000.0,
        'discountPrice': 4190000.0,
        'images': [
          'https://images.unsplash.com/photo-1546054454-aa26e2b734c7?w=800',
        ],
        'specs': {
          'Màn hình': '6.67 inch AMOLED FHD+ 120Hz',
          'Chipset': 'Snapdragon 685',
          'RAM': '6 GB',
          'Bộ nhớ trong': '128 GB',
        },
        'colors': ['Đen', 'Xanh Lá', 'Vàng Cát'],
        'stock': 100,
        'sold': 650,
        'rating': 4.6,
        'reviewCount': 280,
        'tags': ['xiaomi', 'budget'],
        'isActive': true,
        'isFeatured': false,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'prod_pocox6pro',
        'name': 'Xiaomi POCO X6 Pro 5G 12GB/512GB',
        'brand': 'Xiaomi',
        'category': 'cat_xiaomi',
        'description': 'Quái vật hiệu năng gaming giá rẻ, chip Dimensity 8300-Ultra cực bá đạo.',
        'price': 9990000.0,
        'discountPrice': 8490000.0,
        'images': [
          'https://images.unsplash.com/photo-1580910051074-3eb694886505?w=800',
        ],
        'specs': {
          'Màn hình': '6.67 inch Flow AMOLED 120Hz 1.5K',
          'Chipset': 'MediaTek Dimensity 8300-Ultra',
          'RAM': '12 GB',
          'Bộ nhớ trong': '512 GB',
        },
        'colors': ['Vàng POCO', 'Đen', 'Xám'],
        'stock': 40,
        'sold': 150,
        'rating': 4.8,
        'reviewCount': 95,
        'tags': ['xiaomi', 'gaming'],
        'isActive': true,
        'isFeatured': false,
        'createdAt': now,
        'updatedAt': now,
      },

      // --- OPPO ---
      {
        'id': 'prod_oppofindn3',
        'name': 'OPPO Find N3 5G 16GB/512GB',
        'brand': 'OPPO',
        'category': 'cat_oppo',
        'description': 'Đỉnh cao màn hình gập thương gia, camera Hasselblad ấn tượng, mỏng nhẹ bậc nhất.',
        'price': 44990000.0,
        'discountPrice': 41990000.0,
        'images': [
          'https://images.unsplash.com/photo-1580910051074-3eb694886505?w=800',
        ],
        'specs': {
          'Màn hình chính': '7.82 inch OLED 120Hz',
          'Chipset': 'Snapdragon 8 Gen 2',
          'RAM': '16 GB',
          'Bộ nhớ trong': '512 GB',
        },
        'colors': ['Vàng Kim', 'Đen Da'],
        'stock': 8,
        'sold': 15,
        'rating': 4.9,
        'reviewCount': 10,
        'tags': ['oppo', 'foldable'],
        'isActive': true,
        'isFeatured': true,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'prod_opporeno11pro',
        'name': 'OPPO Reno11 Pro 5G 12GB/512GB',
        'brand': 'OPPO',
        'category': 'cat_oppo',
        'description': 'Chuyên gia chân dung nét đỉnh cao, thiết kế mặt lưng đá quý 3D quyến rũ.',
        'price': 16990000.0,
        'discountPrice': 14990000.0,
        'images': [
          'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=800',
        ],
        'specs': {
          'Màn hình': '6.7 inch OLED 120Hz cong',
          'Chipset': 'MediaTek Dimensity 8200',
          'RAM': '12 GB',
          'Bộ nhớ trong': '512 GB',
        },
        'colors': ['Trắng Ngọc', 'Xám San Hạn'],
        'stock': 20,
        'sold': 60,
        'rating': 4.7,
        'reviewCount': 38,
        'tags': ['oppo'],
        'isActive': true,
        'isFeatured': false,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'prod_opporeno11f',
        'name': 'OPPO Reno11 F 5G 8GB/256GB',
        'brand': 'OPPO',
        'category': 'cat_oppo',
        'description': 'Màn hình viền siêu mỏng, kháng nước IP65, sạc nhanh SUPERVOOC 67W.',
        'price': 8990000.0,
        'discountPrice': 7690000.0,
        'images': [
          'https://images.unsplash.com/photo-1546054454-aa26e2b734c7?w=800',
        ],
        'specs': {
          'Màn hình': '6.7 inch AMOLED 120Hz',
          'Chipset': 'Dimensity 7050',
          'RAM': '8 GB',
          'Bộ nhớ trong': '256 GB',
        },
        'colors': ['Xanh Hải Dương', 'Tím Hoa Ánh Kim', 'Đen Cọ'],
        'stock': 35,
        'sold': 110,
        'rating': 4.6,
        'reviewCount': 50,
        'tags': ['oppo', 'budget'],
        'isActive': true,
        'isFeatured': false,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'prod_oppoa79',
        'name': 'OPPO A79 5G 8GB/256GB',
        'brand': 'OPPO',
        'category': 'cat_oppo',
        'description': 'Loa kép bắt tai, màn hình lớn 90Hz mượt mà, sạc 33W SUPERVOOC.',
        'price': 7490000.0,
        'discountPrice': 6290000.0,
        'images': [
          'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800',
        ],
        'specs': {
          'Màn hình': '6.72 inch Sunlight FHD+ 90Hz',
          'Chipset': 'Dimensity 6020',
          'RAM': '8 GB',
          'Bộ nhớ trong': '256 GB',
        },
        'colors': ['Tím Vũ Trụ', 'Đen Dải Ngân Hà'],
        'stock': 40,
        'sold': 90,
        'rating': 4.5,
        'reviewCount': 40,
        'tags': ['oppo', 'budget'],
        'isActive': true,
        'isFeatured': false,
        'createdAt': now,
        'updatedAt': now,
      },

      // --- Phụ kiện ---
      {
        'id': 'prod_airpodspro2',
        'name': 'Tai nghe Apple AirPods Pro 2 USB-C',
        'brand': 'Apple',
        'category': 'cat_accessory',
        'description': 'Chống ồn chủ động ANC gấp 2 lần, chip H2 thông minh, tích hợp cổng sạc USB-C.',
        'price': 6190000.0,
        'discountPrice': 5490000.0,
        'images': [
          'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=800',
        ],
        'specs': {
          'Chipset': 'Apple H2',
          'Kết nối': 'Bluetooth 5.3',
          'Thời lượng pin': '6 giờ (tổng 30 giờ với hộp)',
          'Kháng nước': 'IP54',
        },
        'colors': ['Trắng'],
        'stock': 50,
        'sold': 320,
        'rating': 4.9,
        'reviewCount': 180,
        'tags': ['best_seller', 'apple', 'accessory'],
        'isActive': true,
        'isFeatured': true,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'prod_chargers20w',
        'name': 'Củ sạc nhanh Apple 20W USB-C chính hãng',
        'brand': 'Apple',
        'category': 'cat_accessory',
        'description': 'Sạc nhanh an toàn cho mọi dòng iPhone và iPad, chuẩn Power Delivery 20W.',
        'price': 690000.0,
        'discountPrice': 490000.0,
        'images': [
          'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800',
        ],
        'specs': {
          'Công suất': '20W Power Delivery',
          'Cổng ra': 'USB Type-C',
        },
        'colors': ['Trắng'],
        'stock': 200,
        'sold': 1200,
        'rating': 4.9,
        'reviewCount': 540,
        'tags': ['best_seller', 'accessory'],
        'isActive': true,
        'isFeatured': false,
        'createdAt': now,
        'updatedAt': now,
      },
      {
        'id': 'prod_samsungebp3400',
        'name': 'Pin sạc dự phòng Samsung 10.000mAh 25W',
        'brand': 'Samsung',
        'category': 'cat_accessory',
        'description': 'Sạc siêu nhanh 25W 2 cổng Type-C, chất liệu tái chế thân thiện môi trường.',
        'price': 890000.0,
        'discountPrice': 690000.0,
        'images': [
          'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?w=800',
        ],
        'specs': {
          'Dung lượng': '10.000 mAh',
          'Công suất ra': '25W Super Fast Charging',
        },
        'colors': ['Beige'],
        'stock': 60,
        'sold': 210,
        'rating': 4.8,
        'reviewCount': 88,
        'tags': ['accessory'],
        'isActive': true,
        'isFeatured': false,
        'createdAt': now,
        'updatedAt': now,
      },
    ];

    final batch = _firestore.batch();
    for (final prod in products) {
      final docRef = _firestore.collection('products').doc(prod['id'] as String);
      batch.set(docRef, {
        'name': prod['name'],
        'brand': prod['brand'],
        'category': prod['category'],
        'description': prod['description'],
        'price': prod['price'],
        'discountPrice': prod['discountPrice'],
        'images': prod['images'],
        'specs': prod['specs'],
        'colors': prod['colors'],
        'stock': prod['stock'],
        'sold': prod['sold'],
        'rating': prod['rating'],
        'reviewCount': prod['reviewCount'],
        'tags': prod['tags'],
        'isActive': prod['isActive'],
        'isFeatured': prod['isFeatured'],
        'createdAt': prod['createdAt'],
        'updatedAt': prod['updatedAt'],
      });
    }
    await batch.commit();
    debugPrint('✓ Đã tạo ${products.length} sản phẩm mẫu');
  }

  // ─── 4. Admin User ─────────────────────────────────────────────────────────
  static Future<void> _seedAdminUser() async {
    final adminRef = _firestore.collection('users').doc('admin_demo');
    await adminRef.set({
      'id': 'admin_demo',
      'email': 'admin@smartphonehub.com',
      'displayName': 'Administrator',
      'photoURL': 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200',
      'phoneNumber': '0901234567',
      'role': 'admin',
      'addresses': [],
      'createdAt': DateTime.now(),
      'fcmTokens': [],
    });
    debugPrint('✓ Đã tạo 1 tài khoản Admin mẫu (admin@smartphonehub.com)');
  }
}
